CREATE TABLE MEMBER(
ID VARCHAR2(20) NOT NULL,
PWD VARCHAR2(20) NOT NULL,
NICKNAME VARCHAR2(20) NOT NULL,
SEX CHAR(2) CHECK(SEX IN ('M', 'F')),
CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID),
CONSTRAINT MEMBER_NICKNAME_UQ UNIQUE (NICKNAME)
);

CREATE TABLE BOARD(
NO NUMBER(8) NOT NULL,
NICKNAME VARCHAR(20) NOT NULL,
SUBJECT VARCHAR2(200) NOT NULL,
CONTENT VARCHAR2(2000) NOT NULL,
RECOMMEND NUMBER(8) DEFAULT 0,
DECOMMEND NUMBER(8) DEFAULT 0,
READNUM NUMBER(8) DEFAULT 0,
CONSTRAINT BOARD_NICKNAME_FK FOREIGN KEY (NICKNAME) REFERENCES MEMBER(NICKNAME) ON DELETE CASCADE,
CONSTRAINT BOARD_NO_PK PRIMARY KEY (NO)
);

CREATE SEQUENCE BOARD_SEQ NOCACHE;